name: Build on Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Ensure submodules are checked out
      - run: git submodule update --init --recursive # Ensure submodules are initialized
      - run: npm i && cd src/dto && npm i && cd ../ && npm run build
